[package]
name = "sputnikvm-nostd"
version = "0.1.0"
authors = ["Wei Tang <hi@that.world>"]

[dependencies]
byteorder = { version = "1", default-features = false }
lazy_static = { version = "0.2", path = "./rux/lazy_static", features = ["spin_no_std"] }